[package]
name = "webpy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
#yew = "0.19.3"
seed = "0.9.2"
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["console", "Node", "Element"] }
shared_structs = { path = "../shared_structs" }