description = "Testing the tracer"
status = "Current"

[[Task]]
description = "hello numbers"
info = "Create an integer, a float and a boolean"
help = "No help, you should figure that out on yourself ..."
template = "print('hello world')"
status = "Current"

[[Task]]
description = "hello variables"
info = """Create two variables: a and b
"""
help = "Assign a name to a variable with '='"
template = "print('hello world')"
status = "Current"
